serenity {
  project.name = "QA Training App - Serenity Automation"
  take.screenshots = FOR_FAILURES
  restart.browser.for.each = scenario
  console.colors = true
}

webdriver {
  driver = chrome
  timeouts.implicitlywait = 2000
}

# Headless for CI. For local debugging, remove --headless.
chrome.switches = "--headless,--no-sandbox,--disable-dev-shm-usage,--window-size=1920,1080"

app {
  uiBaseUrl = "http://localhost:8080"
  apiBaseUrl = "http://localhost:8080"
}
